name: mirroring from launchpad
on:
  workflow_dispatch:

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sparkstar/jammy-stable
          fetch-depth: 0
          ref: stable-next
          token: ${{ secrets.TOKEN_PUSH }}
      - name: git config
        run: |
          git config --local user.name sparkstar
          git config --local user.email sparkstar@empal.com
      - name: push updated mirror to github
        run: |
          git remote rm origin
          git remote add origin https://git.launchpad.net/~ubuntu-kernel-stable/+git/jammy
          git fetch -p
          git remote set-url --push origin https://github.com/sparkstar/jammy-stable.git
          git fetch -v --progress -p origin
          git push --mirror
