name: mirroring jammy from launchpad

on:
  schedule:
    - cron: '48 */12 * * *'
  workflow_dispatch:

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sparkstar/jammy-stable
          fetch-depth: 0
          ref: stable-next
          token: ${{ secrets.JAMMY_STABLE_CRON_UPDATE_KERNAL_TOKEN }}
      - name: git config
        run: |
          git config --local user.name sparkstar
          git config --local user.email sparkstar@empal.com
      - name: push updated mirror to github
        run: |
          git remote rm origin
          git remote add origin https://git.launchpad.net/~ubuntu-kernel-stable/+git/jammy
          git fetch -v --progress -p origin
          git pull origin stable-next --ff-only
          git remote set-url --push origin https://github.com/sparkstar/jammy-stable.git
          git push --mirror
