name: mirroring noble from launchpad

on:
  schedule:
    - cron: '48 1,7,13,19 * * *'
  workflow_dispatch:

jobs:
  mirroring-noble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: sparkstar/noble-stable
          fetch-depth: 0
          show-progress: true
          ref: stable-next
          token: ${{ secrets.NOBLE_STABLE_CRON_UPDATE_KERNEL_TOKEN }}
      - name: git config
        run: |
          git config --local user.name sparkstar
          git config --local user.email sparkstar@empal.com
      - name: remove origin and add launchpad git as origin
        run: |
          URL_PUSH=$(git remote get-url origin)
          git remote remove origin
          git remote add origin https://git.launchpad.net/~ubuntu-kernel-stable/+git/noble
          git remote set-url --push origin $URL_PUSH
      - name: fetch all data with tags from fetch-origin to local
        run: |
          # fetch all from fetch-origin(launchpad)
          git fetch --all --verbose --force
          # HEAD from origin
          git reset --hard origin/stable-next
      - name: push latest local to push-origin(github)
        run: |
          git push origin --mirror
